language: java
sudo: true
install: true
os:
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y powershell         ; fi

jdk:
- oraclejdk8

script:
- cd sonar-ps-plugin
- mvn clean test

cache:
  directories:
  - $HOME/.m2
